name: s1_env  
channels:
  - conda-forge  
  - defaults  
dependencies:
  - python=3.9  
  - numpy
  - matplotlib
  - scipy
  - iminuit
  - uncertainties
  - tqdm
  - jupyter
  - pip:
      - sweights  
